server:
  port: 8080
spring:
  application:
    name: asclepius
  redis:
    host: localhost
    port: 6379
    lettuce:
      shutdown-timeout: 3000
      pool:
        max-active: 8
  #    password: thisispassword
  profiles:
    active: test
